name: ✨ Feature Request
description: Suggest a new idea or enhancement for Puzzleit
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Puzzleit! Use this form to suggest a new feature or improvement.

  - type: input
    id: summary
    attributes:
      label: Feature summary
      description: A short title or description of your idea.
      placeholder: "e.g. Add multiplayer puzzle collaboration"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Explain what you want to see added and why it would be helpful.
      placeholder: "It would be great if users could solve puzzles together in real time..."
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case or motivation
      description: How would this feature improve your experience or solve a problem?
      placeholder: "This would help our team use Puzzleit as a collaborative game during retrospectives."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Did you think about other approaches or workarounds?
      placeholder: "We tried splitting screens, but it's hard to coordinate pieces."

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - "Nice to have"
        - "Useful"
        - "Important"
        - "Critical"
      default: 1

  - type: input
    id: email
    attributes:
      label: Email (optional)
      description: Add your email if you'd like us to follow up with you.
      placeholder: "your@email.com"

  - type: markdown
    attributes:
      value: "Thanks for your idea! 🚀 We’ll consider it for future updates to Puzzleit."
